services:
  tunetracker:
    build: .
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=your_mongodb_uri
      - PORT=3001
      - SESSION_SECRET=your_session_secret
      - GOOGLE_CLIENT_ID=your_google_client_id
      - GOOGLE_CLIENT_SECRET=your_google_client_secret
      - NODE_ENV=production
      - CI=true
    volumes:
      - tune_uploads:/usr/src/app/uploads
    restart: unless-stopped

volumes:
  tune_uploads:
