services:
  tunetracker:
    build: .
    ports:
      - "3002:3002"
    environment:
      - MONGO_URI=your_mongodb_uri
      - PORT=3002
      - DEBUG_MODE=false
      - SESSION_SECRET=your_session_secret
      - GOOGLE_CLIENT_ID=your_google_client_id
      - GOOGLE_CLIENT_SECRET=your_google_client_secret
      - NODE_ENV=production
      - MINIO_ACCESS_KEY=your_minio_access_key
      - MINIO_SECRET_KEY=your_minio_secret_key
      - MINIO_ENDPOINT=your_minio_endpoint
      - MINIO_PORT=your_minio_port
      - MAIN_DOMAIN=your_domain_name
      - CI=true
    restart: unless-stopped
    network:
      - bridge

networks:
  bridge:
    external: true
    name: "bridge"
